### ISSUE TITLE
Cant get custom device status

### ISSUE THREAD

**Issue by 1liminal1** [OpenWonderLabs/SwitchBotAPI#64]
I can get a list of devices doing:

curl -H "Authorization:xxxxxxxxxxxxxxxxxxxx" https://api.switch-bot.com/v1.0/devices

I see the device in the list of devices

"infraredRemoteList":[{"deviceId":"xxxxxxxxxxxxxxxxxxxxxx","deviceName":"Bedroom Fan","remoteType":"Others","hubDeviceId":"xxxxxxxxxxxxxxxx"}]}

But If I try to get the status: 

curl -H "Authorization:xxxxxxxxxxxxxxxxxxxxxxxx" https://api.switch-bot.com/v1.0/devices/xxxxxxxxxxxxxxxxxxx/status

I get the following error:

{"statusCode":190,"body":{},"message":"wrong deviceId"}

Also I have added this as a switch into Home Assistant. I have three switchbot and two curtains. all works fine. 

But cant get the fan to do anything

my code 

```
  - platform: template
    switches:
      aircon_switch:
        friendly_name: "Bedroom Fan"
        unique_id: bedroom_fan_switch
        turn_on:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_fan_deviceId
            command: "turnOn"
        turn_off:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_fan_deviceId
            command: "turnOff"
```

Please advise?

Thanks so much :)
