### ISSUE TITLE
MOTION DETECT 0

### ISSUE THREAD

**Issue by Tarusky80** [OpenWonderLabs/SwitchBotAPI#70]
BUG:

MOVEMENT DISPLAY 0 VALUE AND NOT
BRIGHTNESS IS OK... 

MY CODE 

```
# sensoremovimentostudio
- platform: rest
  name: 'sensoremovimentostudio JSON'
  resource: !secret switchbot_sensoremovimentostudio_status_url
  method: GET
  scan_interval: !secret switchbot_scan_interval #600
  headers:
    Authorization: !secret switchbot_api
    Content-Type: 'application/json'
  value_template: '{{ value_json.body }}'
  json_attributes_path: "$.body"
  json_attributes:
    - deviceId 
    - deviceType
    - hubDeviceId
    - moveDetected
    - brightness

- platform: template
  sensors:
    switchbot_sensoremovimentostudio_movement:
      friendly_name: "Sensoremovimentostudio Move"
      value_template: '{{ states.sensor.sensoremovimentostudio_json.attributes["moveDetected"] }}'
    switchbot_sensoremovimentostudio_brightness:
      friendly_name: "Sensoremovimentostudio Bright"
      value_template: '{{ states.sensor.sensoremovimentostudio_json.attributes["brightness"] }}'
```
![ERROR](https://user-images.githubusercontent.com/95435097/146672928-20a4b09a-3b97-444d-a362-b68c2ba4452f.png)
